name: Main
on: push

# TODO - Need to not repeat the checkout and setup node steps...

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }} test
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm t
      - uses: codecov/codecov-action@v5
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v5
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}